version: '3.5'
services:
#  web:
#    build: .
#    ports:
#      - "8033:8033"
  db_settings:
    container_name: db_auth_1
    ports:
      - "5433:5433"
    environment:
      - name=value
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    command: -p 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    image: 'docker_test_6:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db_auth_1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_auth_1:5433/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8033:8033"
volumes:
  postgres-data:
    driver: local

#/var/lib/postgresql/data